[build-system]
requires = ["setuptools>=80.9.0"]
build-backend = "setuptools.build_meta"

[project]
name = "DroneManager"
version = "0.6.0"
authors = [
    {name="Dominik Mattern", email="dominik.mattern@thi.de"},
    {name="Konstantin Bake", email="konstantin.bake@thi.de"},
    {name="Babak Salamat", email="babak.salamat@thi.de"},
    {name="Tim Drouven", email="tim.drouven@thi.de"}, ]
description = "Package to connect to and control multiple drones, either programmatically or using a CLI."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "textual==8.2.*",
    "rich",
    "mavsdk==3.17.*",
    "pymavlink",
    "pygame-ce",
    "haversine",
    "scipy",
    "requests",
    "ruckig>=0.19.4",
    "opencv-python"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent", ]
license = "Apache-2.0"
license-files = ["LICENSE"]

[project.urls]
Repository = "https://github.com/AImotion-Bavaria/DroneManager"
Documentation = "https://dronemanager.readthedocs.io/en/latest/"

[project.scripts]
dm = "dronemanager.app:main"

[project.optional-dependencies]
docs = [
    "sphinx",
    "sphinx_rtd_theme"]

[tool.setuptools.package-data]
dronemanager = ["resources/*"]
