[build-system]
requires = ["setuptools>=80.9.0"]
build-backend = "setuptools.build_meta"

[project]
name = "DroneManager"
version = "0.6.2"
authors = [
    {name="Dominik Mattern", email="dominik.mattern@thi.de"},
    {name="Konstantin Bake", email="konstantin.bake@thi.de"},
    {name="Babak Salamat", email="babak.salamat@thi.de"},
    {name="Tim Drouven", email="tim.drouven@thi.de"}, ]
description = "Package to connect to and control multiple drones, either programmatically or using a CLI."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "textual==8.2.*",
    "rich",
    "mavsdk==3.17.*",
    "pymavlink",
    "pygame-ce",
    "haversine",
    "scipy",
    "requests",
    "ruckig>=0.19.4",
    "opencv-python"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent", ]
license = "Apache-2.0"
license-files = ["LICENSE"]

[project.urls]
Repository = "https://github.com/AImotion-Bavaria/DroneManager"
Documentation = "https://dronemanager.readthedocs.io/en/latest/"

[project.scripts]
dm = "dronemanager.app:main"

[project.optional-dependencies]
docs = [
    "sphinx",
    "sphinx_rtd_theme",
]
tests = [
    "pytest",
    "pytest-asyncio",
    "pytest-cov",
    "flake8",
    "flake8-pyproject",
    "flake8-annotations",
    "pydoclint[flake8]",
    "ruff",
]

[tool.setuptools.package-data]
dronemanager = ["resources/*"]

### Testing configuration ###

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
    "--cov=dronemanager",
    "--cov-report=term-missing"
]
asyncio_mode = "auto"

[tool.coverage.report]
omit = [
    "src/dronemanager/plugins/NatNet/*"
]
fail_under = 80

[tool.flake8]
max-line-length = 120
style = "google"
ignore = [
    "ANN002",
    "ANN003",
    "ANN101",
    "ANN102",
    "DOC607",
#    "DOC602",
#    "DOC603",
]
arg-type-hints-in-docstring = false
check-return-types = false
skip-checking-short-docstrings = false
suppress-none-returning = true
allow-init-docstring = true

only-attrs-with-ClassVar-are-treated-as-class-attrs = true
require-inline-class-var-docs = true

[tool.ruff]
extend-exclude = [
    "src/dronemanager/plugins/NatNet/*",
]

[tool.ruff.lint]
select = ["D", ]
# ignore = ["D107",]

[tool.ruff.lint.pydocstyle]
convention = "google"